version: '3.7'

services:
  db:
    container_name: "test_db"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    ports:
      - "3360:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "social_network"
      MYSQL_USER: "test_db"
      MYSQL_PASSWORD: "secret"
    volumes:
      - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
networks:
  default:
volumes:
  mysql: